### PR TITLE
[Vue] migrate log viewer directive to vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:
* Migrate log viewer directive to vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@diosmosis Saw few functional bugs
1. If any existing request is active and we change the severity level it will no longer cancel the existing XHR request

Screenshot of existing request being cancelled and with proper error message handling
Screenshot from 2022-04-07 07-55-05

Screenshot of request not being cancelled
Screenshot from 2022-04-07 07-57-13

2. The error messages are not shown properly 
Screenshot from 2022-04-07 07-56-41

3. Unable to download the data, there is a JS error in the console
Screenshot from 2022-04-07 08-04-17

**Comment by diosmosis** [comment]
@AltamashShaikh applied the fixes

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@diosmosis 
The request is now cancelled whenever a new one is initiated, but it doesn't display the "Request was possibly aborted" message.

Not important, but earlier when there was a 500 error due to max execution timeout we never showed this error "Oops… there was a problem during the request.." message

Earlier
Screenshot from 2022-04-08 06-28-07

Current
Screenshot from 2022-04-08 06-22-54



Also the download still doesn't work for me, getting the same JS error.

Also noticed this, when 1 request is active and we change something from dropdown the existing request is cancelled and a new request is made,but we also make the request for `loading-blue.gif` again

Screenshot from 2022-04-08 06-10-05

**Comment by diosmosis** [comment]
@AltamashShaikh fixed the issues. The error notification fix requires https://github.com/matomo-org/matomo/pull/19071 to merged in core.

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@diosmosis Most of the things look good now :+1: 
But, the error message is showing "[object] [object]"  for me
Screenshot from 2022-04-11 05-45-08

**Comment by diosmosis** [comment]
@AltamashShaikh can you check you are using https://github.com/matomo-org/matomo/pull/19071 locally? And if its still there after pulling/clearing cache, tell me how you triggered the error?

**Comment by AltamashShaikh** [comment]
@diosmosis All looks good with https://github.com/matomo-org/matomo/pull/19071
:+1:

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
